In [1]:
import numpy
arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [2]:
# usually numpy is imported as np
import numpy as np
print(np.__version__)

1.17.2


## Create a NumPy ndarray Object

In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
arr = [1, 2, 3, 4, 5]
print(arr)
print(type(arr))

[1, 2, 3, 4, 5]
<class 'list'>


In [5]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array((1, 2, 3, 4, 5))

In [7]:
print(arr1)
print(arr2)

[1 2 3 4 5]
[1 2 3 4 5]


In [8]:
print(type(arr1))
print(type(arr2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### Array Dimensions

In [127]:
# 0-D Arrays (scalar)
import numpy as np
arr = np.array(1)
print(arr)
print(type(arr))

1
<class 'numpy.ndarray'>


In [11]:
# 1-D Arrays
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [12]:
# 2-D Arrays (matrix or 2nd order tensors)
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [13]:
# 3-D arrays
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)
print(type(arr))

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>


### Check Number of Dimensions?

In [14]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### Higher Dimensional Arrays

In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


## NumPy Array Indexing

### Access Array Elements

In [128]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])

1


In [18]:
print(arr[1])

2


In [19]:
print(arr[2] + arr[3])

7


### Access 2-D Arrays

In [129]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Get the 2nd element on 1st dimension: ', arr[0, 1])

Get the 2nd element on 1st dimension:  2


In [130]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Get the 5th element on 2nd dimension: ', arr[1, 4])

Get the 5th element on 2nd dimension:  10


### Access 3-D Arrays

In [131]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


### Negative Indexing

In [133]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dimension: ', arr[1, -1])

Last element from 2nd dimension:  10


## Numpy Array Slicing

In [134]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[1:5])

[2 3 4 5]


In [135]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[4:])

[5 6 7 8 9]


In [136]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[:4])

[1 2 3 4]


### Negative Slicing

In [137]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[-3:-1])

[7 8]


### Step

In [140]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr[1:5:2])

[2 4]


In [141]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr[::2])

[1 3 5 7]


### Slicing 2-D Arrays

In [30]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [31]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


In [32]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


## Data Type

### Checking data type

In [33]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [34]:
import numpy as np
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


### Creating Arrays With a Defined Data Type

In [35]:
import numpy as np
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [36]:
import numpy as np
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [37]:
import numpy as np
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

### Converting Data Type on Existing Arrays

In [38]:
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [39]:
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [40]:
import numpy as np
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


### Mathematical operations in NumPy arrays

In [110]:
arr1 = np.array([[4, 7], [2, 6]])
                  
arr2 = np.array([[3, 6], [2, 8]]) 
 
# Addition of two Arrays
print(np.add(arr1, arr2))

[[ 7 13]
 [ 4 14]]


In [112]:
# Addition of array elements
print(np.sum(arr1))

19


In [113]:
# Square root of Array
print(np.sqrt(arr1))

[[2.         2.64575131]
 [1.41421356 2.44948974]]


In [115]:
print(arr1)

[[4 7]
 [2 6]]


In [114]:
# Transpose of Array
print(arr1.T)

[[4 2]
 [7 6]]


## Copy & View

In [41]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [42]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [43]:
# Make a view, change the view, and display both arrays
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31
print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [44]:
# Check if Array Owns it's Data
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


## Shape vs Reshape

In [45]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [46]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


### Reshape From 1-D to 2-D

In [47]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Reshape From 1-D to 3-D

In [48]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [49]:
# Error test
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(3, 3)
print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

### Returns Copy or View?

In [50]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


### Flattening the arrays

In [51]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


## NumPy Array Iterating

### Iterating Arrays

In [52]:
import numpy as np
arr = np.array([1, 2, 3])
for x in arr:
    print(x)

1
2
3


### Iterating 2-D Arrays

In [53]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [54]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


### Iterating 3-D Arrays

In [55]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [56]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


### Iterating Arrays Using nditer()

In [57]:
# Iterating on Each Scalar Element
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [58]:
# Iterating With Different Step Size
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


### Enumerated Iteration Using ndenumerate()

In [59]:
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [60]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


## NumPy Joining Array

In [61]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [62]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


### Joining Arrays Using Stack Functions

In [65]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=0)
print(arr)

[[1 2 3]
 [4 5 6]]


In [68]:
# Stacking Along Rows
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [67]:
# Stacking Along Columns
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [69]:
# Stacking Along Height (depth)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


## NumPy Splitting Array

In [70]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [71]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


### Split into Arrays

In [72]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


### Splitting 2-D Arrays

In [73]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [74]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [75]:
# Split the 2-D array into three 2-D arrays along rows
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [76]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


## NumPy Searching Arrays

In [77]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [78]:
# Find the indexes where the values are even
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [79]:
# Find the indexes where the values are even
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)
print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [80]:
# Find the indexes where the value 7 should be inserted
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

1


In [81]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')
print(x)

2


In [119]:
# argmax() : This function returns indices of the max element of the array in a particular axis.
arr = np.array([1, 2, 3, 9, 4, 5, 6, 7, 8])
print("\nMax element : ", np.argmax(arr))


Max element :  3


In [120]:
# numpy.argmin() : This function returns the indices of the minimum values along an axis
arr = np.array([1, 2, 3, 9, 4, 5, 6, 7, 8])
print("\nMin element : ", np.argmin(arr))


Min element :  0


## NumPy Counting

In [126]:
arr = np.array([[0,1,7,0,0],[3,0,0,2,19]])

print("Number of nonzero values is :", np.count_nonzero(arr))

Number of nonzero values is : 5


## NumPy Sorting Arrays

In [83]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [84]:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [85]:
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


### Sorting a 2-D Array

In [86]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


### argsort()

In [116]:
a = np.array([9, 3, 1, 7, 4, 3, 6])
b = np.argsort(a)
print('Sorted indices of original array->', b)
 
# To get sorted array using sorted indices
# c is temp array created of same len as of b
c = np.zeros(len(b), dtype = int)
for i in range(0, len(b)):
    c[i]= a[b[i]]
print('Sorted array->', c)

Sorted indices of original array-> [2 1 5 4 6 3 0]
Sorted array-> [1 3 3 4 6 7 9]


### lexsort()

In [117]:
a = np.array([9, 3, 1, 3, 4, 3, 6])
b = np.array([4, 6, 9, 2, 1, 8, 7]) 
print('column a, column b')
for (i, j) in zip(a, b):
    print(i, ' ', j)

ind = np.lexsort((b, a)) 
print('Sorted indices->', ind)

column a, column b
9   4
3   6
1   9
3   2
4   1
3   8
6   7
Sorted indices-> [2 3 1 5 4 6 0]


## NumPy Filter Array

In [87]:
# Create an array from the elements on index 0 and 2
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


### Creating the Filter Array

In [88]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
    # if the element is higher than 42, set the value to True, otherwise False:
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [ ]:
# Create a filter array that will return only even elements from the original array
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
    # if the element is completely divisble by 2, set the value to True, otherwise False
    if element % 2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

In [90]:
[x for x in arr if x > 42]

[43, 44]

### Creating Filter Directly From Array

In [91]:
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [92]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


## Random Numbers in NumPy

In [94]:
# Generate Random Number
from numpy import random
x = random.randint(100)
print(x)

24


In [95]:
# Generate Random Float
x = random.rand()
print(x)

0.8386523786346923


In [96]:
# Generate Random Array
x=random.randint(100, size=(5))
print(x)

[21 33 42 31 46]


In [97]:
# 2-D array with 3 rows
x = random.randint(100, size=(3, 5))
print(x)

[[59  5 81 20 20]
 [87 51 61 16 20]
 [75 86  3 65 29]]


In [98]:
x = random.rand(5)
print(x)

[0.29311899 0.78177205 0.39476672 0.74703131 0.07463374]


In [99]:
x = random.rand(3, 5)
print(x)

[[9.29351535e-01 2.32595501e-05 3.66863100e-02 5.93361499e-01
  2.11787464e-01]
 [9.92396596e-01 4.43413620e-01 7.12861433e-01 9.18930489e-01
  3.34370413e-01]
 [7.04165853e-01 6.99819367e-01 1.67948975e-01 8.94959436e-01
  6.69295453e-01]]


### Generate Random Number From Array

In [100]:
x = random.choice([3, 5, 7, 9])
print(x)

7


In [101]:
x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)

[[3 7 3 5 7]
 [3 5 9 3 3]
 [7 3 9 3 3]]


### Random Data Distribution

In [102]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
print(x)

[5 7 5 5 7 7 7 5 5 5 7 7 7 7 7 5 7 7 7 5 7 7 7 5 7 3 3 7 5 5 7 7 3 5 7 7 7
 7 7 7 7 7 7 7 5 5 5 5 7 7 7 7 3 7 5 7 3 7 5 5 7 7 7 5 7 7 7 5 7 5 7 5 7 7
 5 5 7 7 3 7 5 5 5 7 5 7 7 7 7 7 3 7 7 7 7 5 7 3 5 7]


In [105]:
x[x==5]

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5])

In [106]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))
print(x)

[[7 7 5 7 5]
 [7 3 3 7 5]
 [7 7 7 3 7]]


### Random Permutations

In [108]:
arr = np.array([1, 2, 3, 4, 5])
random.shuffle(arr)
print(arr)

[2 5 3 1 4]


In [109]:
arr = np.array([1, 2, 3, 4, 5])
print(random.permutation(arr))

[1 4 5 3 2]
