# NumPy Random

## Random Numbers in NumPy

In [12]:
# Generate Random Number
from numpy import random
x = random.randint(100)
print(x)

32


In [13]:
# Generate Random Float
x = random.rand()
print(x)

0.1013878893895458


In [14]:
# Generate Random Array
x=random.randint(100, size=(5))
print(x)

[19 75 59 61 33]


In [15]:
# 2-D array with 3 rows
x = random.randint(100, size=(3, 5))
print(x)

[[82 13  7 67 62]
 [23  0 22 61  9]
 [31 62 97 17 57]]


In [16]:
# Generate random float array
x = random.rand(5)
print(x)

[0.9737658  0.67364366 0.83487655 0.40009887 0.77472468]


In [17]:
# 2D fload array
x = random.rand(3, 5)
print(x)

[[0.49260385 0.42478077 0.87236632 0.77786356 0.21427693]
 [0.06896446 0.11337551 0.43770502 0.10656788 0.90158798]
 [0.42759182 0.78404057 0.94563358 0.89165175 0.24430325]]


## Random samples

In [25]:
# Random sample 1D
x = random.random_sample() 
print ("Random sample : ", x)

Random sample :  0.7587911387531632


In [26]:
# Random sample 2D array
x = random.random_sample(size=(3,5)) 
print ("Random sample : ", x)

Random sample :  [[0.41198428 0.14868623 0.05833591 0.47681263 0.22343968]
 [0.24085608 0.39310796 0.18740089 0.50738902 0.8243849 ]
 [0.80334977 0.1574967  0.68134134 0.34612825 0.25992801]]


In [27]:
# Random sample 3D array
x = random.random_sample(size=(3,5,1)) 
print ("Random sample : ", x)

Random sample :  [[[0.6364414 ]
  [0.17543847]
  [0.33891284]
  [0.68428701]
  [0.78114128]]

 [[0.1226496 ]
  [0.00438616]
  [0.96924812]
  [0.78780208]
  [0.24453592]]

 [[0.46284358]
  [0.81196274]
  [0.70434131]
  [0.21376747]
  [0.93493878]]]


## Generate Random From Array

In [18]:
x = random.choice([3, 5, 7, 9, 11, 13])
print(x)

11


In [19]:
x = random.choice([3, 5, 7, 9, 11, 13], size=(3, 5))
print(x)

[[13 13 11  7 11]
 [ 5  3  3  9 11]
 [ 3  7  9  9  9]]


## Random Data Distribution

In [20]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
print(x)

[7 7 5 5 5 7 7 5 7 5 7 5 3 5 5 7 7 5 7 5 7 5 7 5 5 7 3 5 7 7 7 7 7 7 7 7 7
 7 7 7 3 5 5 7 7 7 7 7 3 5 3 7 7 7 5 7 7 7 7 5 5 7 7 7 7 7 7 5 7 7 5 7 7 7
 7 7 5 7 7 5 7 7 7 7 7 5 7 5 7 7 5 7 5 7 7 3 5 7 7 5]


In [21]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))
print(x)

[[7 7 7 7 3]
 [5 7 7 7 5]
 [7 7 5 5 5]]


## Random Permutations

In [23]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
random.shuffle(x)
print(x)

[2 6 5 3 8 4 9 1 7]


In [24]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(random.permutation(x))

[8 2 5 7 1 3 6 9 4]


# SciPy Constants

In [1]:
from scipy import constants

print(constants.liter)

0.001


In [2]:
# Print the constant value of PI
print(constants.pi)

3.141592653589793


In [4]:
# List all constants
print(dir(constants))

['Avogadro', 'Boltzmann', 'Btu', 'Btu_IT', 'Btu_th', 'ConstantWarning', 'G', 'Julian_year', 'N_A', 'Planck', 'R', 'Rydberg', 'Stefan_Boltzmann', 'Wien', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_obsolete_constants', 'absolute_import', 'acre', 'alpha', 'angstrom', 'arcmin', 'arcminute', 'arcsec', 'arcsecond', 'astronomical_unit', 'atm', 'atmosphere', 'atomic_mass', 'atto', 'au', 'bar', 'barrel', 'bbl', 'blob', 'c', 'calorie', 'calorie_IT', 'calorie_th', 'carat', 'centi', 'codata', 'constants', 'convert_temperature', 'day', 'deci', 'degree', 'degree_Fahrenheit', 'deka', 'division', 'dyn', 'dyne', 'e', 'eV', 'electron_mass', 'electron_volt', 'elementary_charge', 'epsilon_0', 'erg', 'exa', 'exbi', 'femto', 'fermi', 'find', 'fine_structure', 'fluid_ounce', 'fluid_ounce_US', 'fluid_ounce_imp', 'foot', 'g', 'gallon', 'gallon_US', 'gallon_imp', 'gas_constant', 'gibi', 'giga', 'golden', 'golden_ratio', 'gra

## Metric (SI) Prefixes

In [5]:
print(constants.yotta)    #1e+24
print(constants.zetta)    #1e+21
print(constants.exa)      #1e+18
print(constants.peta)     #1000000000000000.0
print(constants.tera)     #1000000000000.0
print(constants.giga)     #1000000000.0
print(constants.mega)     #1000000.0
print(constants.kilo)     #1000.0
print(constants.hecto)    #100.0
print(constants.deka)     #10.0
print(constants.deci)     #0.1
print(constants.centi)    #0.01
print(constants.milli)    #0.001
print(constants.micro)    #1e-06
print(constants.nano)     #1e-09
print(constants.pico)     #1e-12
print(constants.femto)    #1e-15
print(constants.atto)     #1e-18
print(constants.zepto)    #1e-21

1e+24
1e+21
1e+18
1000000000000000.0
1000000000000.0
1000000000.0
1000000.0
1000.0
100.0
10.0
0.1
0.01
0.001
1e-06
1e-09
1e-12
1e-15
1e-18
1e-21


## Binary Prefixes

In [6]:
print(constants.kibi)    #1024
print(constants.mebi)    #1048576
print(constants.gibi)    #1073741824
print(constants.tebi)    #1099511627776
print(constants.pebi)    #1125899906842624
print(constants.exbi)    #1152921504606846976
print(constants.zebi)    #1180591620717411303424
print(constants.yobi)    #1208925819614629174706176

1024
1048576
1073741824
1099511627776
1125899906842624
1152921504606846976
1180591620717411303424
1208925819614629174706176


## Mass

In [7]:
# Return the specified unit in kg (e.g. gram returns 0.001)
print(constants.gram)        #0.001
print(constants.metric_ton)  #1000.0
print(constants.grain)       #6.479891e-05
print(constants.lb)          #0.45359236999999997
print(constants.pound)       #0.45359236999999997
print(constants.oz)          #0.028349523124999998
print(constants.ounce)       #0.028349523124999998
print(constants.stone)       #6.3502931799999995
print(constants.long_ton)    #1016.0469088
print(constants.short_ton)   #907.1847399999999
print(constants.troy_ounce)  #0.031103476799999998
print(constants.troy_pound)  #0.37324172159999996
print(constants.carat)       #0.0002
print(constants.atomic_mass) #1.66053904e-27
print(constants.m_u)         #1.66053904e-27
print(constants.u)           #1.66053904e-27

0.001
1000.0
6.479891e-05
0.45359236999999997
0.45359236999999997
0.028349523124999998
0.028349523124999998
6.3502931799999995
1016.0469088
907.1847399999999
0.031103476799999998
0.37324172159999996
0.0002
1.6605390666e-27
1.6605390666e-27
1.6605390666e-27


## Angle

In [8]:
# Return the specified unit in radians (e.g. degree returns 0.017453292519943295)
print(constants.degree)     #0.017453292519943295
print(constants.arcmin)     #0.0002908882086657216
print(constants.arcminute)  #0.0002908882086657216
print(constants.arcsec)     #4.84813681109536e-06
print(constants.arcsecond)  #4.84813681109536e-06

0.017453292519943295
0.0002908882086657216
0.0002908882086657216
4.84813681109536e-06
4.84813681109536e-06


## Time

In [9]:
# Return the specified unit in seconds (e.g. hour returns 3600.0)
print(constants.minute)      #60.0
print(constants.hour)        #3600.0
print(constants.day)         #86400.0
print(constants.week)        #604800.0
print(constants.year)        #31536000.0
print(constants.Julian_year) #31557600.0

60.0
3600.0
86400.0
604800.0
31536000.0
31557600.0


## Length

In [10]:
# Return the specified unit in meters (e.g. nautical_mile returns 1852.0)
print(constants.inch)              #0.0254
print(constants.foot)              #0.30479999999999996
print(constants.yard)              #0.9143999999999999
print(constants.mile)              #1609.3439999999998
print(constants.mil)               #2.5399999999999997e-05
print(constants.pt)                #0.00035277777777777776
print(constants.point)             #0.00035277777777777776
print(constants.survey_foot)       #0.3048006096012192
print(constants.survey_mile)       #1609.3472186944373
print(constants.nautical_mile)     #1852.0
print(constants.fermi)             #1e-15
print(constants.angstrom)          #1e-10
print(constants.micron)            #1e-06
print(constants.au)                #149597870691.0
print(constants.astronomical_unit) #149597870691.0
print(constants.light_year)        #9460730472580800.0
print(constants.parsec)            #3.0856775813057292e+16

0.0254
0.30479999999999996
0.9143999999999999
1609.3439999999998
2.5399999999999997e-05
0.00035277777777777776
0.00035277777777777776
0.3048006096012192
1609.3472186944373
1852.0
1e-15
1e-10
1e-06
149597870700.0
149597870700.0
9460730472580800.0
3.085677581491367e+16


## Pressure

In [11]:
# Return the specified unit in pascals (e.g. psi returns 6894.757293168361)
print(constants.atm)         #101325.0
print(constants.atmosphere)  #101325.0
print(constants.bar)         #100000.0
print(constants.torr)        #133.32236842105263
print(constants.mmHg)        #133.32236842105263
print(constants.psi)         #6894.757293168361

101325.0
101325.0
100000.0
133.32236842105263
133.32236842105263
6894.757293168361
